# .travis.yml
language: csharp
dist: trusty
dotnet: 2.1.300
mono: none
solution: Everhour.Net.sln
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet restore
  - dotnet build
  - dotnet test Everhour.Net.Tests/Everhour.Net.Tests.csproj